[workspace]
members = [
    "amalgam",
    "arena",
    "bespin",
    "kryo",
    "kylo",
    "loco",
    "micron",
    "motive",
    "serf",
    "subzero",
    "synchrony",
    "vader",
    "xcom",
    "yoda",
]
